Workflow correct error handling

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -17,8 +17,8 @@ jobs:
         if: ${{ github.event.workflow_run.conclusion == 'failure' }}
         run: exit 1
 
-      - name: Force Failure
-        run: exit 1
+      #- name: Force Failure
+      #  run: exit 1
 
       - name: Configure SSH
         run: |
