Workflow Successful

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -30,9 +30,13 @@ jobs:
       - name: Run Tests
         run: ./run_test.sh
 
-      - name: Force Failure
-        run: exit 1
+      #- name: Force Failure
+       # run: exit 1
       
+      - name: Tests Successeded
+        if: ${{ failure() }} 
+        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content= Tests Succeeded"
+
       - name: Failure to Deploy Site
         if: ${{ failure() }} 
         run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Tests Failed"
