Improved Error Handling GitHub Actions

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -29,7 +29,10 @@ jobs:
 
       - name: Run Tests
         run: ./run_test.sh
+        
+     # - name: Force Failure
+      #  run: exit 1
       
       - name: Failure to Deploy Site
         if: ${{ failure() }} 
-        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment Failed"
+        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Tests Failed"
